### ISSUE TITLE
Runtime errors with 0.12.0 - RuntimeError: BITTREX: QUANTITY_NOT_PROVIDED

### ISSUE THREAD

**Issue by moosylog** [timkpaine/algo-coin#31]
Let me start with kudos for the dev team !!

After the upgrade to 0.12.0 I had several crashes with a 

Traceback (most recent call last):
  File "./freqtrade/main.py", line 249, in app
    _process()
  File "./freqtrade/main.py", line 57, in _process
    handle_trade(trade)
  File "./freqtrade/main.py", line 139, in handle_trade
    execute_sell(trade, current_rate)
  File "./freqtrade/main.py", line 92, in execute_sell
    profit = trade.exec_sell_order(current_rate, balance)
  File "/root/freqtrade-master/freqtrade/persistence.py", line 79, in exec_sell_order
    order_id = exchange.sell(str(self.pair), rate, amount)
  File "/root/freqtrade-master/freqtrade/exchange/__init__.py", line 78, in sell
    return EXCHANGE.sell(pair, rate, amount)
  File "/root/freqtrade-master/freqtrade/exchange/bittrex.py", line 48, in sell
    raise RuntimeError('{}: {}'.format(self.name.upper(), data['message']))
RuntimeError: BITTREX: QUANTITY_NOT_PROVIDED

and

2017-10-26 11:39:58,083 - freqtrade.analyze - DEBUG - buy_trigger: 2017-10-26T09:30:00 (pair=BTC_TIME, signal=False)
2017-10-26 11:39:58,431 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/root/freqtrade-master/.env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/root/freqtrade-master/.env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 171, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/root/freqtrade-master/freqtrade/rpc/telegram.py", line 79, in wrapper
    return command_handler(*args, **kwargs)
  File "/root/freqtrade-master/freqtrade/rpc/telegram.py", line 259, in _forcesell
    profit = trade.exec_sell_order(current_rate, balance)
  File "/root/freqtrade-master/freqtrade/persistence.py", line 79, in exec_sell_order
    order_id = exchange.sell(str(self.pair), rate, amount)
  File "/root/freqtrade-master/freqtrade/exchange/__init__.py", line 78, in sell
    return EXCHANGE.sell(pair, rate, amount)
  File "/root/freqtrade-master/freqtrade/exchange/bittrex.py", line 48, in sell
    raise RuntimeError('{}: {}'.format(self.name.upper(), data['message']))
RuntimeError: BITTREX: QUANTITY_NOT_PROVIDED

**Comment by timkpaine** [comment]
definitely not the right package
